"""
services/face_service.py - face detection, embedding, and matching
"""
import io
import uuid
import base64
import json
import os

import numpy as np
from PIL import Image

# DeepFace import can fail on machines that globally force legacy Keras.
os.environ.pop("TF_USE_LEGACY_KERAS", None)
from deepface import DeepFace
import mediapipe as mp

from config import settings
from services.supabase_client import get_supabase


_MP_FACE_DETECTOR = None

_DEEPFACE_MODELS = {
    "VGG-Face",
    "Facenet",
    "Facenet512",
    "OpenFace",
    "DeepFace",
    "DeepID",
    "ArcFace",
    "Dlib",
    "SFace",
    "GhostFaceNet",
}


def _canonical_face_model(raw_model: str | None) -> str:
    aliases = {
        "vggface": "VGG-Face",
        "facenet": "Facenet",
        "facenet512": "Facenet512",
        "openface": "OpenFace",
        "deepface": "DeepFace",
        "deepid": "DeepID",
        "arcface": "ArcFace",
        "dlib": "Dlib",
        "sface": "SFace",
        "ghostfacenet": "GhostFaceNet",
    }
    key = (raw_model or "").strip().replace("_", "").replace("-", "").lower()
    model = aliases.get(key, "Facenet512")
    if model not in _DEEPFACE_MODELS:
        return "Facenet512"
    return model


def _b64_to_image(b64: str) -> np.ndarray:
    data = base64.b64decode(b64)
    img = Image.open(io.BytesIO(data)).convert("RGB")
    return np.array(img)


def _get_mediapipe_detector():
    global _MP_FACE_DETECTOR
    if _MP_FACE_DETECTOR is not None:
        return _MP_FACE_DETECTOR

    _MP_FACE_DETECTOR = mp.solutions.face_detection.FaceDetection(
        model_selection=0,
        min_detection_confidence=float(settings.face_detection_confidence or 0.7),
    )
    return _MP_FACE_DETECTOR


def _clamp_box_with_padding(x: int, y: int, w: int, h: int, img_w: int, img_h: int, pad_ratio: float = 0.12) -> tuple[int, int, int, int]:
    pad_w = int(w * pad_ratio)
    pad_h = int(h * pad_ratio)
    x1 = max(0, x - pad_w)
    y1 = max(0, y - pad_h)
    x2 = min(img_w, x + w + pad_w)
    y2 = min(img_h, y + h + pad_h)
    return x1, y1, x2, y2


def _extract_faces_mediapipe(image_array: np.ndarray, enforce_detection: bool = True) -> list[dict]:
    detector = _get_mediapipe_detector()
    detections = detector.process(image_array).detections

    if not detections:
        if enforce_detection:
            raise ValueError("No face detected by MediaPipe")
        return []

    img_h, img_w = image_array.shape[:2]
    max_faces = max(1, int(settings.face_max_faces_per_frame or 2))
    faces: list[dict] = []

    for detection in detections[:max_faces]:
        rel = detection.location_data.relative_bounding_box

        x = int(rel.xmin * img_w)
        y = int(rel.ymin * img_h)
        w = int(rel.width * img_w)
        h = int(rel.height * img_h)

        if w <= 0 or h <= 0:
            continue

        x1, y1, x2, y2 = _clamp_box_with_padding(x, y, w, h, img_w, img_h)
        if x2 <= x1 or y2 <= y1:
            continue

        crop = image_array[y1:y2, x1:x2]
        if crop.size == 0:
            continue

        faces.append(
            {
                "face": crop.astype(np.float32) / 255.0,
                "facial_area": {"x": x1, "y": y1, "w": x2 - x1, "h": y2 - y1},
                "confidence": float(detection.score[0]) if detection.score else 1.0,
            }
        )

    if enforce_detection and not faces:
        raise ValueError("No valid face crop generated by MediaPipe")
    return faces


def _canonical_detector_backend(raw_backend: str | None) -> str:
    """
    Normalize detector backend names to DeepFace-accepted strings.
    """
    key = (raw_backend or "").strip().lower().replace("_", "").replace("-", "")
    aliases = {
        "retinaface": "retinaface",
        "mtcnn": "mtcnn",
        "opencv": "opencv",
        "ssd": "ssd",
        "dlib": "dlib",
        "mediapipe": "mediapipe",
        "yolov8": "yolov8",
        "yunet": "yunet",
        "fastmtcnn": "fastmtcnn",
        "centerface": "centerface",
        "skip": "skip",
    }
    # Default to a fast, commonly available option.
    return aliases.get(key, raw_backend or "yunet")


def _extract_faces_deepface(
    image_array: np.ndarray,
    detector_backend: str,
    enforce_detection: bool = True,
) -> list[dict]:
    """
    Face detection + alignment using DeepFace.
    Returns the subset of fields expected by the rest of the app.
    """
    faces = DeepFace.extract_faces(
        img_path=image_array,
        detector_backend=detector_backend,
        enforce_detection=enforce_detection,
        align=True,
        expand_percentage=0,
        grayscale=False,
        anti_spoofing=False,
    )

    out: list[dict] = []
    for f in faces:
        face = f.get("face")
        region = (f.get("facial_area") or {}).copy()

        for k in ("x", "y", "w", "h"):
            if k in region:
                region[k] = int(region[k])

        out.append(
            {
                "face": np.asarray(face, dtype=np.float32),
                "facial_area": region,
                "confidence": float(f.get("confidence", 1.0) if f.get("confidence", None) is not None else 1.0),
            }
        )

    return out


def extract_faces_with_fallback(image_array: np.ndarray, enforce_detection: bool = True) -> list[dict]:
    detector_backend = _canonical_detector_backend(getattr(settings, "face_detector_backend", None))

    # Primary: DeepFace detector backends (e.g., yunet / yolov8 / retinaface).
    # Fallback: MediaPipe crops (keeps things running if a backend fails).
    try:
        return _extract_faces_deepface(
            image_array=image_array,
            detector_backend=detector_backend,
            enforce_detection=enforce_detection,
        )
    except Exception:
        return _extract_faces_mediapipe(image_array, enforce_detection=enforce_detection)


def get_embedding(image_array: np.ndarray) -> list[float]:
    """
    Compute an embedding from an already-cropped face.
    This avoids re-detecting faces inside the embedding step.
    """
    if image_array is None:
        return []

    img = np.asarray(image_array)

    if img.dtype != np.uint8:
        # If it's a normalized float crop, convert to uint8.
        max_val = float(np.max(img)) if img.size else 0.0
        if max_val <= 1.5:
            img = (img * 255.0).clip(0, 255).astype(np.uint8)
        else:
            img = img.clip(0, 255).astype(np.uint8)

    result = DeepFace.represent(
        img_path=img,
        model_name=_canonical_face_model(settings.face_model),
        enforce_detection=False,
        detector_backend="skip",
        align=False,
    )
    if not result:
        return []

    embedding = result[0].get("embedding", [])
    return embedding if isinstance(embedding, list) else list(embedding)


def cosine_distance(a: list[float], b: list[float]) -> float:
    va, vb = np.array(a), np.array(b)
    denom = float(np.linalg.norm(va) * np.linalg.norm(vb))
    if denom <= 1e-12:
        return 1.0
    return float(1 - np.dot(va, vb) / denom)


def cosine_similarity(a: list[float], b: list[float]) -> float:
    return float(1.0 - cosine_distance(a, b))


def _as_embedding_list(raw_embedding) -> list[list[float]]:
    value = json.loads(raw_embedding) if isinstance(raw_embedding, str) else raw_embedding
    if not value:
        return []

    if isinstance(value, list) and value and isinstance(value[0], (int, float)):
        return [value]

    if isinstance(value, list) and value and isinstance(value[0], list):
        return [v for v in value if isinstance(v, list) and v]

    return []


def identify_person_from_image(image_array: np.ndarray) -> dict | None:
    embedding = get_embedding(image_array)
    return find_matching_person(embedding)


def find_matching_person(embedding: list[float]) -> dict | None:
    sb = get_supabase()
    rows = sb.table("persons").select("id, name, role, face_embedding").execute().data
    best_match = None
    best_similarity = float(settings.face_similarity_threshold)
    legacy_best_dist = float(settings.face_distance_threshold)

    for row in rows:
        embeddings = _as_embedding_list(row.get("face_embedding"))
        if not embeddings:
            continue

        person_best_similarity = max(cosine_similarity(embedding, stored) for stored in embeddings)
        person_best_distance = 1.0 - person_best_similarity

        if person_best_similarity >= best_similarity:
            best_similarity = person_best_similarity
            best_match = row
            continue

        if best_match is None and person_best_distance <= legacy_best_dist:
            legacy_best_dist = person_best_distance
            best_match = row

    return best_match


def register_person(embedding: list[float] | list[list[float]], role: str = "person", name: str | None = None) -> dict:
    sb = get_supabase()
    stored_embedding = embedding

    payload = {
        "id": str(uuid.uuid4()),
        "name": name,
        "role": role,
        "face_embedding": json.dumps(stored_embedding),
    }
    result = sb.table("persons").insert(payload).execute()
    return result.data[0]


def register_person_from_images(images: list[np.ndarray], role: str = "person", name: str | None = None) -> dict:
    embeddings: list[list[float]] = [get_embedding(img) for img in images]
    return register_person(embeddings if len(embeddings) > 1 else embeddings[0], role=role, name=name)


def upload_face_image(image_array: np.ndarray, person_id: str) -> str:
    sb = get_supabase()
    img = Image.fromarray(image_array)
    buf = io.BytesIO()
    img.save(buf, format="JPEG")
    buf.seek(0)
    path = f"{person_id}/{uuid.uuid4()}.jpg"
    sb.storage.from_(settings.supabase_storage_bucket).upload(path, buf.read(), {"content-type": "image/jpeg"})
    url = sb.storage.from_(settings.supabase_storage_bucket).get_public_url(path)
    return url
